/*
 * This source file was generated by the Gradle 'init' task
 */
package info.rx00405.test.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestClientMainTest {
    @Test void appHasAGreeting() {
        TestClientMain classUnderTest = new TestClientMain();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
