/*
 * This source file was generated by the Gradle 'init' task
 */
package info.rx00405.test.client;

public class TestClientMain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new TestClientMain().getGreeting());
    }
}
